-- Esquema canónico del CMS
--
-- El esquema se gestiona mediante migraciones versionadas para que los cambios
-- sean reproducibles y reversibles. Aplica, en orden, los archivos de:
--
--   supabase/migrations/
--
-- La primera migración consolidada es:
--   202608080001_phase1_rbac.sql
--
-- No vuelvas a definir aquí tablas sueltas: hacerlo separaría el entorno local
-- del historial aplicado en Supabase.
